### ISSUE TITLE
please add rule to align around //

### ISSUE THREAD

**Issue by justrajdeep** [junegunn/vim-easy-align#93] opened 2016-10-27 18:52 UTC
Hi

I often work with files where i want to align the comments,

Please add a rule to align around `//`

Thanks

**Comment by junegunn** [comment] 2016-10-28 17:46
I may add it to the default set of rules, but for now you can add this to your vimrc

```vim
let g:easy_align_delimiters = {
\ '/': { 'pattern': '//\+', 'delimiter_align': 'l', 'ignore_groups': ['!Comment'] }
\ }
```

(Duplicate of #53)

**Closed by junegunn** 2016-10-28 17:46 UTC
